### ISSUE TITLE
Page de gestion du plugin vide

### ISSUE THREAD

**Issue by kevvv31** [cazeaux/jeedom_pushbullet#13]
Bonjour,

J'ai depuis quelque temps une erreur sur ce plugin. La page est vide et lorsque la page est actualisée (F5) elle montre tout avec des {{}} et les commandes ne répondent pas (impossible de naviguer).

J'ai tout désinstallé, réinstallé, changé d'OS etc.. rien à faire.
Le même problème à été détecté et résolue pour ce plugin: https://github.com/jeedom-zigate/jeedom-plugin-zigate/issues/205

**Pour Reproduire**
Etapes pour reproduire le problème dans Jeedom:

1. Cliquer sur 'Plugins/Communication/Pushbullet'

**Fonctionnement attendu**
L'installation s'est bien déroulée et le démon a démarré.
Lorsque je rafraichis la page, les menus apparaissent avec des accolades {{ }} et rien ne se passe

L'équipement déjà créé auparavant fonctionne toujours, je reçcois notifications sur mon smartphone, mais je ne peux plus ajouter ou modifier déquipement.

**Screenshot:**
![image](https://user-images.githubusercontent.com/35462144/91836866-ac8f5b80-ec4b-11ea-8f30-9d0b622b4d7b.png)

**Informations:**

Hardware: RPI 3B
Version Debian : Buster 64 (version officielle sur page d'installation de jeedom jeedom-debian-buster-rpi-64-4.0.61.zip)
Version Jeedom : 4.0.61
Version Plugin : 2020-02-18 04:14:14

Merci d'avance,
Kévin

**Comment by mso-29** [comment]
Bonjour Kévin,
J'ai exactement le même problème que toi et j'ai trouvé une solution qui convient pour ce plugin mais aussi pour d'autres:
Depuis le passage à la version 4 de Jeedom, certains objets de "base' ont été remplacés. 
Dans notre cas, il faut modifier le fichier /var/www/html/plugins/pushbullet/desktop/php/pushbullet.php ligne 68: 
foreach (**object**::all() as $object) {                                          
Par
foreach (**jeeObject**::all() as $object) {
Normalement, tu devrais voir apparaitre de nouveau la page de configuration, sans avoir à redémarrer quoi que ce soit.

Cordialement,
Michel

**Comment by kevvv31** [comment]
> Bonjour Kévin,
> J'ai exactement le même problème que toi et j'ai trouvé une solution qui convient pour ce plugin mais aussi pour d'autres:
> Depuis le passage à la version 4 de Jeedom, certains objets de "base' ont été remplacés.
> Dans notre cas, il faut modifier le fichier /var/www/html/plugins/pushbullet/desktop/php/pushbullet.php ligne 68:
> foreach (**object**::all() as $object) {
> Par
> foreach (**jeeObject**::all() as $object) {
> Normalement, tu devrais voir apparaitre de nouveau la page de configuration, sans avoir à redémarrer quoi que ce soit.
> 
> Cordialement,
> Michel

Bonjour Michel,

Merci merci merci!!! C'était tout simple à résoudre et ca marche parfaitement! Depuis le temps que je traine ce problème.. c'est génial! je peux à nouveau utiliser ce plugin (que j'aime bcp pour ce qui est notifications sur iPhone).
Maintenant que je comprend la raison j'essaiera de réparer certains autres plugins avec le même problème!

J'espère que ca pourra en aider d'autres.

Cordialement,
Kévin
