### ISSUE TITLE
Suppression des bootstrapSwitch non supportée pas la V3

### ISSUE THREAD

**Issue by ZitouneOlivier** [cazeaux/jeedom_pushbullet#6]
je te propose la correction pour les virer ?

**Comment by cazeaux** [comment]
Je veux bien, si tu as déjà ciblé la correction. Tu peux faire un pull request ?

**Comment by ZitouneOlivier** [comment]
J'ai déjà fait le correction chez moi, dès que j'ai le temps de comprendre
comment marche ghit je te fais ça 😊

**Comment by dough29** [comment]
Merci pour ta participation Olivier.

Concrètement il te faudra :
- faire un fork de ce repo mais apparemment c'est déjà fait
- récupérer les sources de ton fork sur ta machine (git, sourcetree, ... perso j'utilise sourcetree)
- appliquer ta/tes modification(s)
- faire un commit + push de ces modifications
- faire le pull request depuis GitHUB

N'hésite pas si besoin !

**Comment by ZitouneOlivier** [comment]
A mon avis c'est bon, tu dois avoir la modification, dsl pour la lenteur mais je n'ai jamais utilisé Git.. Je t'avoue que je trouve ça bordélique. Mais bon c'est juste une histoire de comprendre comment ça marche..
- Fork >> Je recupère tes source
- Je fais mes modifs.
- Je fais un commit pour déclarer mes modifs ( A priori j'ai du créer un nouvelle branche pour ces modif)
- Puis je fais un push pour te les envoyer.
- Puis je vais sur le git et je Pull-request pour les publier chez toi...

C'est bien ça ?

**Comment by dough29** [comment]
Oui ce sont des process assez compliqués vu de loin mais une fois rodé ça se fait plutôt bien.

C'est exactement comme tu le décris.

**Comment by ZitouneOlivier** [comment]
Ben je te laisse vérifier, mais bon les modification sont sommaires :-)

**Comment by dough29** [comment]
Je ne suis pas le maintainer de ce repo, juste un simple contributeur :-P

On va attendre sagement que cazeaux passe par là ^^

**Comment by cazeaux** [comment]
Merci, je regarde tout ça !

**Comment by cazeaux** [comment]
Solved in v2.80
